version: '3'

services:
  labs_upb_iee:
    build: .
    ports:
      - "8080:8080"
    environment:
      DB_DIALECT: org.hibernate.dialect.MySQL8Dialect
      DB_PASSWORD: root
      DB_URL: jdbc:mysql://10.38.32.138:3306/lab_upb?createDataBaseIfNotExist&serverTimezone=America/Bogota
      DB_USER_NAME: root
      JWT_EXPIRATION: 86400000
      JWT_REFRESH_EXPIRATION: 604800000
      JWT_SECRET_KEY: 89FvU9vE5kn88BlJEQ4ua6RNVnNnLZ7ht9VK8JWSYyIZtTKUfgUcZ8YnRBaSLQgnPV6Cm5Pr+AgqhvwMpuCC75dFQXz3agMKKyCRIxEI0/0=
    restart:
        always
    depends_on:
        lab_upb:
            condition: service_healthy
  lab_upb:
    image: mysql:8.0.33
    ports:
        - "3307:3306"
    environment:
        MYSQL_PASSWORD: root
        MYSQL_DATABASE: lab_upb
        MYSQL_ROOT_PASSWORD: root
    restart:
        always
    healthcheck:
        test: ["CMD", "mysqladmin" ,"ping", "-h", "localhost"]
        timeout: 10s
        retries: 10
